---
title: "Assignment 6 Code"
output: html_document
date: "2024-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(dplyr)
library(tidyverse)
library(readr)
library(readxl)
library(sf)
library(scales)
library(tidycensus)
library(maps)
```

## Load the data
```{r}
df_2019 <- read.csv("E:\\CUNY SPS\\Fall 2024\\DATA 608\\Assignment 6\\dec19pub.csv")
df_2020 <- read.csv("E:\\CUNY SPS\\Fall 2024\\DATA 608\\Assignment 6\\dec20pub.csv")
df_2021 <- read.csv("E:\\CUNY SPS\\Fall 2024\\DATA 608\\Assignment 6\\dec21pub.csv")
df_2022 <- read.csv("E:\\CUNY SPS\\Fall 2024\\DATA 608\\Assignment 6\\dec22pub.csv")
df_2023 <- read.csv("E:\\CUNY SPS\\Fall 2024\\DATA 608\\Assignment 6\\dec23pub.csv")
```
##Selecting vars to keep
```{r}
unique(df_2019$HEFAMINC)

df_2020_red <- df_2020 %>% select(c(HRHHID, HRYEAR4, HRFS12M8, HRFS12MC, HEFAMINC, GESTFIPS, GTMETSTA, PTDTRACE, PRNMCHLD, PEEDUCA, PRTAGE, PESEX))
df_2021_red <- df_2021 %>% select(c(HRHHID, HRYEAR4, HRFS12M8, HRFS12MC, HEFAMINC, GESTFIPS, GTMETSTA, PTDTRACE, PRNMCHLD, PEEDUCA, PRTAGE, PESEX))
df_2022_red <- df_2022 %>% select(c(HRHHID, HRYEAR4, HRFS12M8, HRFS12MC, HEFAMINC, GESTFIPS, GTMETSTA, PTDTRACE, PRNMCHLD, PEEDUCA, PRTAGE, PESEX))
df_2023_red <- df_2023 %>% select(c(HRHHID, HRYEAR4, HRFS12M8, HRFS12MC, HEFAMINC, GESTFIPS, GTMETSTA, PTDTRACE, PRNMCHLD, PEEDUCA, PRTAGE, PESEX))

df_2020$GESTFIPS
df_2023$GESTFIPS

unique(df_2020_red$PESEX)
str(df_2020_red$PRTAGE)

```

##Recode State Vars
```{r}
df_2020_red <- df_2020_red %>% 
   mutate(
    state = case_when(
      GESTFIPS == "1" ~ "AL",
      GESTFIPS == "2" ~ "AK",
      GESTFIPS == "4" ~ "AZ",
      GESTFIPS == "5" ~ "AR",
      GESTFIPS == "6" ~ "CA",
      GESTFIPS == "8" ~ "CO",
      GESTFIPS == "9" ~ "CT",
      GESTFIPS == "10" ~ "DE",
      GESTFIPS == "11" ~ "DC",
      GESTFIPS == "12" ~ "FL",
      GESTFIPS == "13" ~ "GA",
      GESTFIPS == "15" ~ "HI",
      GESTFIPS == "16" ~ "ID",
      GESTFIPS == "17" ~ "IL",
      GESTFIPS == "18" ~ "IN",
      GESTFIPS == "19" ~ "IA",
      GESTFIPS == "20" ~ "KS",
      GESTFIPS == "21" ~ "KY",
      GESTFIPS == "22" ~ "LA",
      GESTFIPS == "23" ~ "ME",
      GESTFIPS == "24" ~ "MD",
      GESTFIPS == "25" ~ "MA",
      GESTFIPS == "26" ~ "MI",
      GESTFIPS == "27" ~ "MN",
      GESTFIPS == "28" ~ "MS",
      GESTFIPS == "29" ~ "MO",
      GESTFIPS == "30" ~ "MT",
      GESTFIPS == "31" ~ "NE",
      GESTFIPS == "32" ~ "NV",
      GESTFIPS == "33" ~ "NH",
      GESTFIPS == "34" ~ "NJ",
      GESTFIPS == "35" ~ "NM",
      GESTFIPS == "36" ~ "NY",
      GESTFIPS == "37" ~ "NC",
      GESTFIPS == "38" ~ "ND",
      GESTFIPS == "39" ~ "OH",
      GESTFIPS == "40" ~ "OK",
      GESTFIPS == "41" ~ "OR",
      GESTFIPS == "42" ~ "PA",
      GESTFIPS == "44" ~ "RI",
      GESTFIPS == "45" ~ "SC",
      GESTFIPS == "46" ~ "SD",
      GESTFIPS == "47" ~ "TN",
      GESTFIPS == "48" ~ "TX",
      GESTFIPS == "49" ~ "UT",
      GESTFIPS == "50" ~ "VT",
      GESTFIPS == "51" ~ "VA",
      GESTFIPS == "53" ~ "WA",
      GESTFIPS == "54" ~ "WV",
      GESTFIPS == "55" ~ "WI",
      GESTFIPS == "56" ~ "WY",
      TRUE ~ NA_character_ # Handle unmatched cases
    )
  )

df_2020_red <- df_2020_red %>% select(-GESTFIPS)

df_2021_red <- df_2021_red %>% 
   mutate(
    state = case_when(
      GESTFIPS == "1" ~ "AL",
      GESTFIPS == "2" ~ "AK",
      GESTFIPS == "4" ~ "AZ",
      GESTFIPS == "5" ~ "AR",
      GESTFIPS == "6" ~ "CA",
      GESTFIPS == "8" ~ "CO",
      GESTFIPS == "9" ~ "CT",
      GESTFIPS == "10" ~ "DE",
      GESTFIPS == "11" ~ "DC",
      GESTFIPS == "12" ~ "FL",
      GESTFIPS == "13" ~ "GA",
      GESTFIPS == "15" ~ "HI",
      GESTFIPS == "16" ~ "ID",
      GESTFIPS == "17" ~ "IL",
      GESTFIPS == "18" ~ "IN",
      GESTFIPS == "19" ~ "IA",
      GESTFIPS == "20" ~ "KS",
      GESTFIPS == "21" ~ "KY",
      GESTFIPS == "22" ~ "LA",
      GESTFIPS == "23" ~ "ME",
      GESTFIPS == "24" ~ "MD",
      GESTFIPS == "25" ~ "MA",
      GESTFIPS == "26" ~ "MI",
      GESTFIPS == "27" ~ "MN",
      GESTFIPS == "28" ~ "MS",
      GESTFIPS == "29" ~ "MO",
      GESTFIPS == "30" ~ "MT",
      GESTFIPS == "31" ~ "NE",
      GESTFIPS == "32" ~ "NV",
      GESTFIPS == "33" ~ "NH",
      GESTFIPS == "34" ~ "NJ",
      GESTFIPS == "35" ~ "NM",
      GESTFIPS == "36" ~ "NY",
      GESTFIPS == "37" ~ "NC",
      GESTFIPS == "38" ~ "ND",
      GESTFIPS == "39" ~ "OH",
      GESTFIPS == "40" ~ "OK",
      GESTFIPS == "41" ~ "OR",
      GESTFIPS == "42" ~ "PA",
      GESTFIPS == "44" ~ "RI",
      GESTFIPS == "45" ~ "SC",
      GESTFIPS == "46" ~ "SD",
      GESTFIPS == "47" ~ "TN",
      GESTFIPS == "48" ~ "TX",
      GESTFIPS == "49" ~ "UT",
      GESTFIPS == "50" ~ "VT",
      GESTFIPS == "51" ~ "VA",
      GESTFIPS == "53" ~ "WA",
      GESTFIPS == "54" ~ "WV",
      GESTFIPS == "55" ~ "WI",
      GESTFIPS == "56" ~ "WY",
      TRUE ~ NA_character_ # Handle unmatched cases
    )
  )

df_2021_red <- df_2021_red %>% select(-GESTFIPS)

df_2022_red <- df_2022_red %>% 
   mutate(
    state = case_when(
      GESTFIPS == "1" ~ "AL",
      GESTFIPS == "2" ~ "AK",
      GESTFIPS == "4" ~ "AZ",
      GESTFIPS == "5" ~ "AR",
      GESTFIPS == "6" ~ "CA",
      GESTFIPS == "8" ~ "CO",
      GESTFIPS == "9" ~ "CT",
      GESTFIPS == "10" ~ "DE",
      GESTFIPS == "11" ~ "DC",
      GESTFIPS == "12" ~ "FL",
      GESTFIPS == "13" ~ "GA",
      GESTFIPS == "15" ~ "HI",
      GESTFIPS == "16" ~ "ID",
      GESTFIPS == "17" ~ "IL",
      GESTFIPS == "18" ~ "IN",
      GESTFIPS == "19" ~ "IA",
      GESTFIPS == "20" ~ "KS",
      GESTFIPS == "21" ~ "KY",
      GESTFIPS == "22" ~ "LA",
      GESTFIPS == "23" ~ "ME",
      GESTFIPS == "24" ~ "MD",
      GESTFIPS == "25" ~ "MA",
      GESTFIPS == "26" ~ "MI",
      GESTFIPS == "27" ~ "MN",
      GESTFIPS == "28" ~ "MS",
      GESTFIPS == "29" ~ "MO",
      GESTFIPS == "30" ~ "MT",
      GESTFIPS == "31" ~ "NE",
      GESTFIPS == "32" ~ "NV",
      GESTFIPS == "33" ~ "NH",
      GESTFIPS == "34" ~ "NJ",
      GESTFIPS == "35" ~ "NM",
      GESTFIPS == "36" ~ "NY",
      GESTFIPS == "37" ~ "NC",
      GESTFIPS == "38" ~ "ND",
      GESTFIPS == "39" ~ "OH",
      GESTFIPS == "40" ~ "OK",
      GESTFIPS == "41" ~ "OR",
      GESTFIPS == "42" ~ "PA",
      GESTFIPS == "44" ~ "RI",
      GESTFIPS == "45" ~ "SC",
      GESTFIPS == "46" ~ "SD",
      GESTFIPS == "47" ~ "TN",
      GESTFIPS == "48" ~ "TX",
      GESTFIPS == "49" ~ "UT",
      GESTFIPS == "50" ~ "VT",
      GESTFIPS == "51" ~ "VA",
      GESTFIPS == "53" ~ "WA",
      GESTFIPS == "54" ~ "WV",
      GESTFIPS == "55" ~ "WI",
      GESTFIPS == "56" ~ "WY",
      TRUE ~ NA_character_ # Handle unmatched cases
    )
  )

df_2022_red <- df_2022_red %>% select(-GESTFIPS)

df_2023_red <- df_2023_red %>% 
   mutate(
    state = case_when(
      GESTFIPS == "1" ~ "AL",
      GESTFIPS == "2" ~ "AK",
      GESTFIPS == "4" ~ "AZ",
      GESTFIPS == "5" ~ "AR",
      GESTFIPS == "6" ~ "CA",
      GESTFIPS == "8" ~ "CO",
      GESTFIPS == "9" ~ "CT",
      GESTFIPS == "10" ~ "DE",
      GESTFIPS == "11" ~ "DC",
      GESTFIPS == "12" ~ "FL",
      GESTFIPS == "13" ~ "GA",
      GESTFIPS == "15" ~ "HI",
      GESTFIPS == "16" ~ "ID",
      GESTFIPS == "17" ~ "IL",
      GESTFIPS == "18" ~ "IN",
      GESTFIPS == "19" ~ "IA",
      GESTFIPS == "20" ~ "KS",
      GESTFIPS == "21" ~ "KY",
      GESTFIPS == "22" ~ "LA",
      GESTFIPS == "23" ~ "ME",
      GESTFIPS == "24" ~ "MD",
      GESTFIPS == "25" ~ "MA",
      GESTFIPS == "26" ~ "MI",
      GESTFIPS == "27" ~ "MN",
      GESTFIPS == "28" ~ "MS",
      GESTFIPS == "29" ~ "MO",
      GESTFIPS == "30" ~ "MT",
      GESTFIPS == "31" ~ "NE",
      GESTFIPS == "32" ~ "NV",
      GESTFIPS == "33" ~ "NH",
      GESTFIPS == "34" ~ "NJ",
      GESTFIPS == "35" ~ "NM",
      GESTFIPS == "36" ~ "NY",
      GESTFIPS == "37" ~ "NC",
      GESTFIPS == "38" ~ "ND",
      GESTFIPS == "39" ~ "OH",
      GESTFIPS == "40" ~ "OK",
      GESTFIPS == "41" ~ "OR",
      GESTFIPS == "42" ~ "PA",
      GESTFIPS == "44" ~ "RI",
      GESTFIPS == "45" ~ "SC",
      GESTFIPS == "46" ~ "SD",
      GESTFIPS == "47" ~ "TN",
      GESTFIPS == "48" ~ "TX",
      GESTFIPS == "49" ~ "UT",
      GESTFIPS == "50" ~ "VT",
      GESTFIPS == "51" ~ "VA",
      GESTFIPS == "53" ~ "WA",
      GESTFIPS == "54" ~ "WV",
      GESTFIPS == "55" ~ "WI",
      GESTFIPS == "56" ~ "WY",
      TRUE ~ NA_character_ # Handle unmatched cases
    )
  )

df_2023_red <- df_2023_red %>% select(-GESTFIPS)
```

## Recode Food Security Status (Adults)
```{r}

#df_2020 %>% select(HRFS12MC) %>% View()

##2020
df_2020_red <- df_2020_red %>% 
  mutate(
    food_sec_adult = case_when(
      HRFS12M8 == "-9" ~ "No Response",
      HRFS12M8 == "1" ~ "High",
      HRFS12M8 == "2" ~ "Marginal",
      HRFS12M8 == "3" ~ "Low",
      HRFS12M8 == "4" ~ "Very Low"
    )
  )

df_2020_red <- df_2020_red %>%  
  mutate(
    food_sec_child = case_when(
      HRFS12MC == "-9" ~ "No Response",
      HRFS12MC == "1" ~ "High or Marginal",
      HRFS12MC == "2" ~ "Low",
      HRFS12MC == "3" ~ "Very Low",
    )
  )

df_2020_red <- df_2020_red %>%  
  mutate(fam_income = case_when(
        HEFAMINC == 1 ~ "LESS THAN $5,000",
    HEFAMINC == 2 ~ "5,000 TO 7,499",
    HEFAMINC == 3 ~ "7,500 TO 9,999",
    HEFAMINC == 4 ~ "10,000 TO 12,499",
    HEFAMINC == 5 ~ "12,500 TO 14,999",
    HEFAMINC == 6 ~ "15,000 TO 19,999",
    HEFAMINC == 7 ~ "20,000 TO 24,999",
    HEFAMINC == 8 ~ "25,000 TO 29,999",
    HEFAMINC == 9 ~ "30,000 TO 34,999",
    HEFAMINC == 10 ~ "35,000 TO 39,999",
    HEFAMINC == 11 ~ "40,000 TO 49,999",
    HEFAMINC == 12 ~ "50,000 TO 59,999",
    HEFAMINC == 13 ~ "60,000 TO 74,999",
    HEFAMINC == 14 ~ "75,000 TO 99,999",
    HEFAMINC == 15 ~ "100,000 TO 149,999",
    HEFAMINC == 16 ~ "150,000 OR MORE",
    TRUE ~ NA_character_
  ))

unique(df_2020_red$fam_income)

df_2020_red <- df_2020_red %>%  
  mutate(fam_poverty = case_when(
    fam_income < 15000 ~ "Poverty",
    fam_income >= 15000 & fam_income < 30000 ~ "Low Income",
    fam_income >= 30000 & fam_income < 50000 ~ "Lower-Middle Class",
    fam_income >= 50000 & fam_income < 100000 ~ "Upper-Middle Class",
    fam_income >= 100000 ~ "Rich",
    TRUE ~ NA_character_ # Handle unexpected values
  ))

df_2020_red <- df_2020_red %>% 
  mutate(region = case_when(
    GTMETSTA == 1 ~ "Metropolitan",
    GTMETSTA == 2 ~ "Non-Metropolitan",
    GTMETSTA == 3 ~ "Not Identified"
  ))

df_2020_red <- df_2020_red %>%
  mutate(race = case_when(
    PTDTRACE == 1 ~ "White",
    PTDTRACE == 2 ~ "Black",
    PTDTRACE == 3 ~ "American Indian or Alaskan Native",
    PTDTRACE == 4 ~ "Asian",
    PTDTRACE == 5 ~ "Hawaiian",
    PTDTRACE >= 6 ~ "More than one race"
  ))

df_2020_red <- df_2020_red %>%
  mutate(num_children = PRNMCHLD)

df_2020_red <- df_2020_red %>%
  mutate(num_children = ifelse(num_children == -1, 0, num_children))

df_2020_red <- df_2020_red %>%
  mutate(education = case_when(
    PEEDUCA > 31 & PEEDUCA < 39 ~ "Education Not Completed",
    PEEDUCA == 39 ~ "High School Education",
    PEEDUCA == 40 ~ "Some College",
    PEEDUCA > 40 & PEEDUCA < 43 ~ "College Education",
    PEEDUCA > 43 ~ "Graduate Education",
    TRUE ~ "Other/Unknown"  # Default case
  ))

##2021

df_2021_red <- df_2021_red %>% 
  mutate(
    food_sec_adult = case_when(
      HRFS12M8 == "-9" ~ "No Response",
      HRFS12M8 == "1" ~ "High",
      HRFS12M8 == "2" ~ "Marginal",
      HRFS12M8 == "3" ~ "Low",
      HRFS12M8 == "4" ~ "Very Low"
    )
  )

df_2021_red <- df_2021_red %>%  
  mutate(
    food_sec_child = case_when(
      HRFS12MC == "-9" ~ "No Response",
      HRFS12MC == "1" ~ "High or Marginal",
      HRFS12MC == "2" ~ "Low",
      HRFS12MC == "3" ~ "Very Low"
    )
  )

df_2021_red <- df_2021_red %>%  
  mutate(fam_income = case_when(
        HEFAMINC == 1 ~ "LESS THAN $5,000",
    HEFAMINC == 2 ~ "5,000 TO 7,499",
    HEFAMINC == 3 ~ "7,500 TO 9,999",
    HEFAMINC == 4 ~ "10,000 TO 12,499",
    HEFAMINC == 5 ~ "12,500 TO 14,999",
    HEFAMINC == 6 ~ "15,000 TO 19,999",
    HEFAMINC == 7 ~ "20,000 TO 24,999",
    HEFAMINC == 8 ~ "25,000 TO 29,999",
    HEFAMINC == 9 ~ "30,000 TO 34,999",
    HEFAMINC == 10 ~ "35,000 TO 39,999",
    HEFAMINC == 11 ~ "40,000 TO 49,999",
    HEFAMINC == 12 ~ "50,000 TO 59,999",
    HEFAMINC == 13 ~ "60,000 TO 74,999",
    HEFAMINC == 14 ~ "75,000 TO 99,999",
    HEFAMINC == 15 ~ "100,000 TO 149,999",
    HEFAMINC == 16 ~ "150,000 OR MORE",
    TRUE ~ NA_character_
  ))

df_2021_red <- df_2021_red %>%  
  mutate(fam_poverty = case_when(
    fam_income < 15000 ~ "Poverty",
    fam_income >= 15000 & fam_income < 30000 ~ "Low Income",
    fam_income >= 30000 & fam_income < 50000 ~ "Lower-Middle Class",
    fam_income >= 50000 & fam_income < 100000 ~ "Upper-Middle Class",
    fam_income >= 100000 ~ "Rich",
    TRUE ~ NA_character_ # Handle unexpected values
  ))

df_2021_red <- df_2021_red %>% 
  mutate(region = case_when(
    GTMETSTA == 1 ~ "Metropolitan",
    GTMETSTA == 2 ~ "Non-Metropolitan",
    GTMETSTA == 3 ~ "Not Identified"
  ))

df_2021_red <- df_2021_red %>%
  mutate(race = case_when(
    PTDTRACE == 1 ~ "White",
    PTDTRACE == 2 ~ "Black",
    PTDTRACE == 3 ~ "American Indian or Alaskan Native",
    PTDTRACE == 4 ~ "Asian",
    PTDTRACE == 5 ~ "Hawaiian",
    PTDTRACE >= 6 ~ "More than one race"
  ))

df_2021_red <- df_2021_red %>%
  mutate(num_children = PRNMCHLD)

df_2021_red <- df_2021_red %>%
  mutate(num_children = ifelse(num_children == -1, 0, num_children))

df_2021_red <- df_2021_red %>%
  mutate(education = case_when(
    PEEDUCA > 31 & PEEDUCA < 39 ~ "Education Not Completed",
    PEEDUCA == 39 ~ "High School Education",
    PEEDUCA == 40 ~ "Some College",
    PEEDUCA > 40 & PEEDUCA < 43 ~ "College Education",
    PEEDUCA > 43 ~ "Graduate Education",
    TRUE ~ "Other/Unknown"  # Default case
  ))

##2022

df_2022_red <- df_2022_red %>% 
  mutate(
    food_sec_adult = case_when(
      HRFS12M8 == "-9" ~ "No Response",
      HRFS12M8 == "1" ~ "High",
      HRFS12M8 == "2" ~ "Marginal",
      HRFS12M8 == "3" ~ "Low",
      HRFS12M8 == "4" ~ "Very Low"
    )
  )

df_2022_red <- df_2022_red %>%  
  mutate(
    food_sec_child = case_when(
      HRFS12MC == "-9" ~ "No Response",
      HRFS12MC == "1" ~ "High or Marginal",
      HRFS12MC == "2" ~ "Low",
      HRFS12MC == "3" ~ "Very Low",
    )
  )

df_2022_red <- df_2022_red %>%  
  mutate(fam_income = case_when(
        HEFAMINC == 1 ~ "LESS THAN $5,000",
    HEFAMINC == 2 ~ "5,000 TO 7,499",
    HEFAMINC == 3 ~ "7,500 TO 9,999",
    HEFAMINC == 4 ~ "10,000 TO 12,499",
    HEFAMINC == 5 ~ "12,500 TO 14,999",
    HEFAMINC == 6 ~ "15,000 TO 19,999",
    HEFAMINC == 7 ~ "20,000 TO 24,999",
    HEFAMINC == 8 ~ "25,000 TO 29,999",
    HEFAMINC == 9 ~ "30,000 TO 34,999",
    HEFAMINC == 10 ~ "35,000 TO 39,999",
    HEFAMINC == 11 ~ "40,000 TO 49,999",
    HEFAMINC == 12 ~ "50,000 TO 59,999",
    HEFAMINC == 13 ~ "60,000 TO 74,999",
    HEFAMINC == 14 ~ "75,000 TO 99,999",
    HEFAMINC == 15 ~ "100,000 TO 149,999",
    HEFAMINC == 16 ~ "150,000 OR MORE",
    TRUE ~ NA_character_
  ))

df_2022_red <- df_2022_red %>%  
  mutate(fam_poverty = case_when(
    fam_income < 15000 ~ "Poverty",
    fam_income >= 15000 & fam_income < 30000 ~ "Low Income",
    fam_income >= 30000 & fam_income < 50000 ~ "Lower-Middle Class",
    fam_income >= 50000 & fam_income < 100000 ~ "Upper-Middle Class",
    fam_income >= 100000 ~ "Rich",
    TRUE ~ NA_character_ # Handle unexpected values
  ))

df_2022_red <- df_2022_red %>% 
  mutate(region = case_when(
    GTMETSTA == 1 ~ "Metropolitan",
    GTMETSTA == 2 ~ "Non-Metropolitan",
    GTMETSTA == 3 ~ "Not Identified"
  ))

df_2022_red <- df_2022_red %>%
  mutate(race = case_when(
    PTDTRACE == 1 ~ "White",
    PTDTRACE == 2 ~ "Black",
    PTDTRACE == 3 ~ "American Indian or Alaskan Native",
    PTDTRACE == 4 ~ "Asian",
    PTDTRACE == 5 ~ "Hawaiian",
    PTDTRACE >= 6 ~ "More than one race"
  ))

df_2022_red <- df_2022_red %>%
  mutate(num_children = PRNMCHLD)

df_2022_red <- df_2022_red %>%
  mutate(num_children = ifelse(num_children == -1, 0, num_children))

df_2022_red <- df_2022_red %>%
  mutate(education = case_when(
    PEEDUCA > 31 & PEEDUCA < 39 ~ "Education Not Completed",
    PEEDUCA == 39 ~ "High School Education",
    PEEDUCA == 40 ~ "Some College",
    PEEDUCA > 40 & PEEDUCA < 43 ~ "College Education",
    PEEDUCA > 43 ~ "Graduate Education",
    TRUE ~ "Other/Unknown"  # Default case
  ))

##2023

df_2023_red <- df_2023_red %>% 
  mutate(
    food_sec_adult = case_when(
      HRFS12M8 == "-9" ~ "No Response",
      HRFS12M8 == "1" ~ "High",
      HRFS12M8 == "2" ~ "Marginal",
      HRFS12M8 == "3" ~ "Low",
      HRFS12M8 == "4" ~ "Very Low"
    )
  )

df_2023_red <- df_2023_red %>%  
  mutate(
    food_sec_child = case_when(
      HRFS12MC == "-9" ~ "No Response",
      HRFS12MC == "1" ~ "High or Marginal",
      HRFS12MC == "2" ~ "Low",
      HRFS12MC == "3" ~ "Very Low",
    )
  )

df_2023_red <- df_2023_red %>%  
  mutate(fam_income = case_when(
        HEFAMINC == 1 ~ "LESS THAN $5,000",
    HEFAMINC == 2 ~ "5,000 TO 7,499",
    HEFAMINC == 3 ~ "7,500 TO 9,999",
    HEFAMINC == 4 ~ "10,000 TO 12,499",
    HEFAMINC == 5 ~ "12,500 TO 14,999",
    HEFAMINC == 6 ~ "15,000 TO 19,999",
    HEFAMINC == 7 ~ "20,000 TO 24,999",
    HEFAMINC == 8 ~ "25,000 TO 29,999",
    HEFAMINC == 9 ~ "30,000 TO 34,999",
    HEFAMINC == 10 ~ "35,000 TO 39,999",
    HEFAMINC == 11 ~ "40,000 TO 49,999",
    HEFAMINC == 12 ~ "50,000 TO 59,999",
    HEFAMINC == 13 ~ "60,000 TO 74,999",
    HEFAMINC == 14 ~ "75,000 TO 99,999",
    HEFAMINC == 15 ~ "100,000 TO 149,999",
    HEFAMINC == 16 ~ "150,000 OR MORE",
    TRUE ~ NA_character_
  ))

df_2023_red <- df_2023_red %>%  
  mutate(fam_poverty = case_when(
    fam_income < 15000 ~ "Poverty",
    fam_income >= 15000 & fam_income < 30000 ~ "Low Income",
    fam_income >= 30000 & fam_income < 50000 ~ "Lower-Middle Class",
    fam_income >= 50000 & fam_income < 100000 ~ "Upper-Middle Class",
    fam_income >= 100000 ~ "Rich",
    TRUE ~ NA_character_ # Handle unexpected values
  ))

df_2023_red <- df_2023_red %>% 
  mutate(region = case_when(
    GTMETSTA == 1 ~ "Metropolitan",
    GTMETSTA == 2 ~ "Non-Metropolitan",
    GTMETSTA == 3 ~ "Not Identified"
  ))

df_2023_red <- df_2023_red %>%
  mutate(race = case_when(
    PTDTRACE == 1 ~ "White",
    PTDTRACE == 2 ~ "Black",
    PTDTRACE == 3 ~ "American Indian or Alaskan Native",
    PTDTRACE == 4 ~ "Asian",
    PTDTRACE == 5 ~ "Hawaiian",
    PTDTRACE >= 6 ~ "More than one race"
  ))

df_2023_red <- df_2023_red %>%
  mutate(num_children = PRNMCHLD)

df_2023_red <- df_2023_red %>%
  mutate(num_children = ifelse(num_children == -1, 0, num_children))

df_2023_red <- df_2023_red %>%
  mutate(education = case_when(
    PEEDUCA > 31 & PEEDUCA < 39 ~ "Education Not Completed",
    PEEDUCA == 39 ~ "High School Education",
    PEEDUCA == 40 ~ "Some College",
    PEEDUCA > 40 & PEEDUCA < 43 ~ "College Education",
    PEEDUCA > 43 ~ "Graduate Education",
    TRUE ~ "Other/Unknown"  # Default case
  ))

df_2020_red <- df_2020_red %>% select(-c(HRFS12M8:PEEDUCA))
df_2021_red <- df_2021_red %>% select(-c(HRFS12M8:PEEDUCA))
df_2022_red <- df_2022_red %>% select(-c(HRFS12M8:PEEDUCA))
df_2023_red <- df_2023_red %>% select(-c(HRFS12M8:PEEDUCA))

df_2020_red <- df_2020_red %>% rename(Age = PRTAGE, Sex = PESEX) %>% mutate(Age = ifelse(Age == -1, NA, Age), Sex = ifelse(Sex == -1, NA, Sex))
df_2021_red <- df_2021_red %>% rename(Age = PRTAGE, Sex = PESEX) %>% mutate(Age = ifelse(Age == -1, NA, Age), Sex = ifelse(Sex == -1, NA, Sex))
df_2022_red <- df_2022_red %>% rename(Age = PRTAGE, Sex = PESEX) %>% mutate(Age = ifelse(Age == -1, NA, Age), Sex = ifelse(Sex == -1, NA, Sex))
df_2023_red <- df_2023_red %>% rename(Age = PRTAGE, Sex = PESEX) %>% mutate(Age = ifelse(Age == -1, NA, Age), Sex = ifelse(Sex == -1, NA, Sex))
```

##Append time
```{r}
df_full <- bind_rows(df_2020_red, df_2021_red)

df_full <- bind_rows(df_full, df_2022_red)

df_full <- bind_rows(df_full, df_2023_red)
```

##############Visualizations###################

```{r}
length(unique(df_full$HRHHID))
unique(df_full$food_sec_child)
```

###GEOGRAPHIC HEATMAP CHILDREN
```{r fig.width=10, fig.height=6}



df_full <- df_full %>%
  mutate(comb_sec_adult = case_when(
    str_detect(food_sec_adult, regex("High|Marginal", ignore_case = TRUE)) ~ "High or Marginal",
    str_detect(food_sec_adult, regex("Low|Very Low", ignore_case = TRUE)) ~ "Low or Very Low",
    TRUE ~ "Unknown"
  ))

unique(df_full$food_sec_child)

df_full <- df_full %>%
  mutate(comb_sec_child = case_when(
    str_detect(food_sec_child, regex("High or Marginal", ignore_case = T)) ~ "High or Marginal",
    str_detect(food_sec_child, regex("Low|Very Low", ignore_case = TRUE)) ~ "Low or Very Low",
    TRUE ~ NA
  ))

#df_full$state_rcd <- tolower(df_full$state)

df_sec_freq <- df_full %>%
  filter(!is.na(comb_sec_child) & comb_sec_child != -1) %>%
  group_by(state, comb_sec_child) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(state) %>%
  mutate(percentage = (count / sum(count)) * 100)

df_sec_freq_Low <- df_sec_freq %>% 
  filter(comb_sec_child == "Low or Very Low")

states <- map_data("state")

df_sec_freq_Low$state <- tolower(state.name[match(df_sec_freq_Low$state, state.abb)])
df_sec_freq_Low <- df_sec_freq_Low %>% filter(!is.na(state))

map_data <- left_join(states, df_sec_freq_Low, by = c("region" = "state"))

options(repr.plot.width = 10, repr.plot.height = 6)

ggplot(map_data, aes(x = long, y = lat, group = group, fill = percentage)) +
  geom_polygon(color = "black") +
  coord_fixed(1.3) + # Replace coord_map with coord_fixed for stability
  scale_fill_viridis_c(option = "turbo", na.value = "grey") +
  labs(
    fill = "Percentage Food Insecure Children",
    title = "Map of Low Food Security Among Children by U.S. State"
  ) +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
# 
# avg_state_heat_child <- df_full %>%
#   group_by(Jobs_Group, State) %>% 
#   summarise(med_salary = median(Mean_Salary)) %>% 
#   arrange(desc(med_salary))
# 
# avg_state_heat <- avg_state_heat %>% filter(State != "")
# 
# avg_state_heat <- avg_state_heat %>% filter(!is.na(State))
# 
# map <- avg_state %>% select(State)
# 
# centroids <- centroids %>% rename(State = state_abbr)
# 
# avg_state_heat <- semi_join(avg_state_heat, centroids, by = "State")
# 
# avg_state_heat %>% ggplot(aes(reorder(Jobs_Group, -med_salary), reorder(State, med_salary), fill = med_salary)) +
#   scale_fill_gradient(low = "blue", high = "red") +
#   geom_tile() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#   labs(fill = "Median Salary",
#        x = "Job Title",
#        y = "State",
#          title = "Heatmap of Median Salaries by U.S. State")
```


##GEOGRAPHIC HEATMAP ADULTS

```{r}
df_sec_freq_adult <- df_full %>%
  filter(!is.na(comb_sec_adult) & comb_sec_adult != -1 & comb_sec_adult != "Unknown") %>%
  group_by(state, comb_sec_adult) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(state) %>%
  mutate(percentage = (count / sum(count)) * 100)

df_sec_freq_adult_Low <- df_sec_freq_adult %>% 
  filter(comb_sec_adult == "Low or Very Low")

states <- map_data("state")

df_sec_freq_adult_Low$state <- tolower(state.name[match(df_sec_freq_adult_Low$state, state.abb)])
df_sec_freq_adult_Low <- df_sec_freq_adult_Low %>% filter(!is.na(state))

map_data <- left_join(states, df_sec_freq_adult_Low, by = c("region" = "state"))

options(repr.plot.width = 10, repr.plot.height = 6)

ggplot(map_data, aes(x = long, y = lat, group = group, fill = percentage)) +
  geom_polygon(color = "black") +
  coord_fixed(1.3) + # Replace coord_map with coord_fixed for stability
  scale_fill_viridis_c(option = "turbo", na.value = "grey") +
  labs(
    fill = "Percentage Food Insecure Adults",
    title = "Map of Low Food Security Among Adults by U.S. State"
  ) +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
```


##Recode fam_poverty...
```{r}
df_full <- df_full %>%
  mutate(fam_poverty = case_when(
    str_detect(fam_income, "LESS THAN \\$5,000|5,000 TO 7,499|7,500 TO 9,999|10,000 TO 12,499|12,500 TO 14,999") ~ "Poverty",
    str_detect(fam_income, "15,000 TO 19,999|20,000 TO 24,999|25,000 TO 29,999") ~ "Low Income",
    str_detect(fam_income, "30,000 TO 34,999|35,000 TO 39,999|40,000 TO 49,999") ~ "Lower-Middle Class",
    str_detect(fam_income, "50,000 TO 59,999|60,000 TO 74,999|75,000 TO 99,999") ~ "Middle Class",
    str_detect(fam_income, "100,000 TO 149,999|150,000 OR MORE") ~ "Rich",
    TRUE ~ NA_character_ # Handles unmatched cases
  ))

```

##Child and Adult Food Insecurity Over the Years

```{r}
df_child_freq_year <- df_full %>%
  filter(!is.na(comb_sec_child) & comb_sec_child != -1) %>%
  group_by(HRYEAR4, comb_sec_child) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(HRYEAR4) %>%
  mutate(percentage = (count / sum(count)) * 100)

df_adult_freq_year <- df_full %>%
  filter(!is.na(comb_sec_adult) & comb_sec_adult != -1 & comb_sec_adult != "Unknown") %>%
  group_by(HRYEAR4, comb_sec_adult) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(HRYEAR4) %>%
  mutate(percentage = (count / sum(count)) * 100)

df_child_freq_year <- df_child_freq_year %>%
  rename(comb_sec = comb_sec_child) %>%
  mutate(child_adult = "Child")

df_adult_freq_year <- df_adult_freq_year %>%
  rename(comb_sec = comb_sec_adult) %>%
  mutate(child_adult = "Adult")

df_full_freq_year <- bind_rows(df_adult_freq_year, df_child_freq_year)
df_full_freq_year <- df_full_freq_year %>% filter(comb_sec != "High or Marginal")

ggplot(df_full_freq_year, aes(x = HRYEAR4, y = percentage, color = child_adult)) +
  geom_line(size = 1.2) +  
  geom_point(size = 3, shape = 21, fill = "white", stroke = 1.2) + 
  theme_classic(base_size = 14) +  
  labs(
    title = "Change in Low Child and Adult Food Security Prevalence Over Time",
    x = "Year",  # Corrected label for x-axis
    y = "Percentage (%)",  # Added y-axis label
    color = "Age Group"  # Legend title
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  # Centered bold title
    legend.position = "top",  # Move legend to the top
    legend.title = element_text(face = "bold")  # Bold legend title
  )
```

##Region and Food Security

```{r}

unique(df_full$region)

df_adult_freq_region <- df_full %>%
  filter(!is.na(comb_sec_adult) & comb_sec_adult != -1 & comb_sec_adult != "Unknown") %>%
  filter(!is.na(region) & region != "Not Identified") %>%
  group_by(region, comb_sec_adult) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(region) %>%
  mutate(percentage = (count / sum(count)) * 100) %>%
  filter(comb_sec_adult != "High or Marginal")

df_child_freq_region <- df_full %>%
  filter(!is.na(comb_sec_child) & comb_sec_child != -1 & comb_sec_child != "Unknown") %>%
  filter(!is.na(region) & region != "Not Identified") %>%
  group_by(region, comb_sec_child) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(region) %>%
  mutate(percentage = (count / sum(count)) * 100) %>%
  filter(comb_sec_child != "High or Marginal")

#df_adult_freq_region <- df_adult_freq_region %>% rename(comb_sec=comb_sec_adult)
df_adult_freq_region <- df_adult_freq_region %>% mutate(child_adult = "Adult")
#df_child_freq_region <- df_child_freq_region %>% rename(comb_sec=comb_sec_child)
df_child_freq_region <- df_child_freq_region %>% mutate(child_adult = "Child")

df_full_freq_region <- bind_rows(df_adult_freq_region, df_child_freq_region)

  
ggplot(df_full_freq_region, aes(x = region, y = percentage, fill = child_adult)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  labs(title = "Low Food Security in the U.S. by Region Type", x = "Region", y = "Percentage of Low Food Security (%)", fill = "Age Group") +
  theme_classic()
```

##Food Security and Poverty Level

```{r}

unique(df_full$fam_poverty)
df_adult_freq_pov <- df_full %>%
  filter(!is.na(comb_sec_adult) & comb_sec_adult != -1 & comb_sec_adult != "Unknown") %>%
  filter(!is.na(fam_poverty)) %>%
  group_by(fam_poverty, comb_sec_adult) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(fam_poverty) %>%
  mutate(percentage = (count / sum(count)) * 100) %>%
  filter(comb_sec_adult != "High or Marginal")

df_child_freq_pov <- df_full %>%
  filter(!is.na(comb_sec_child) & comb_sec_child != -1 & comb_sec_child != "Unknown") %>%
  filter(!is.na(fam_poverty)) %>%
  group_by(fam_poverty, comb_sec_child) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(fam_poverty) %>%
  mutate(percentage = (count / sum(count)) * 100) %>%
  filter(comb_sec_child != "High or Marginal")

df_adult_freq_pov <- df_adult_freq_pov %>% rename(comb_sec=comb_sec_adult)
df_adult_freq_pov <- df_adult_freq_pov %>% mutate(child_adult = "Adult")
df_child_freq_pov <- df_child_freq_pov %>% rename(comb_sec=comb_sec_child)
df_child_freq_pov <- df_child_freq_pov %>% mutate(child_adult = "Child")

df_full_freq_pov <- bind_rows(df_adult_freq_pov, df_child_freq_pov)


df_summary <- df_full %>%
  group_by(fam_poverty, education) %>%
  summarise(
    percentage_low = mean(food_sec_child == "Low", na.rm = TRUE) * 100,
    .groups = "drop"
  )

df_summary <- df_summary %>%
  complete(fam_poverty, education, fill = list(percentage_low = 0))

df_summary <- df_summary %>%
  filter(!is.na(fam_poverty ))


unique(df_summary$fam_poverty)
df_summary <- df_summary %>% mutate(fam_poverty = factor(fam_poverty, levels = c("Poverty", "Low Income", "Lower-Middle Class", "Middle Class", "Rich")))

unique(df_summary$education)
df_summary <- df_summary %>% mutate(education = factor(education, levels = c("Other/Unknown", "Education Not Completed", "High School Education", "Some College", "College Education", "Graduate Education")))

ggplot(df_summary, aes(x = fam_poverty, y = education, fill = percentage_low)) +
  geom_tile(color = "white") +
  labs(
    title = "Low Food Security in Children by Family Education and Poverty Level",
    x = "Poverty Level",
    y = "Education Level",
    fill = "Percentage\nLow Food Security"
  ) +
  scale_fill_viridis_c(option = "turbo", direction = 1) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5)
  )
```

##
```{r}
df_summary_adult <- df_full %>%
  group_by(fam_poverty, education) %>%
  summarise(
    percentage_low = mean(food_sec_adult == "Low", na.rm = TRUE) * 100,
    .groups = "drop"
  )

df_summary_adult <- df_summary_adult %>%
  complete(fam_poverty, education, fill = list(percentage_low = 0))

df_summary_adult <- df_summary_adult %>%
  filter(!is.na(fam_poverty ))


unique(df_summary_adult$fam_poverty)
df_summary_adult <- df_summary_adult %>% mutate(fam_poverty = factor(fam_poverty, levels = c("Poverty", "Low Income", "Lower-Middle Class", "Middle Class", "Rich")))

unique(df_summary_adult$education)
df_summary_adult <- df_summary_adult %>% mutate(education = factor(education, levels = c("Other/Unknown", "Education Not Completed", "High School Education", "Some College", "College Education", "Graduate Education")))

ggplot(df_summary_adult, aes(x = fam_poverty, y = education, fill = percentage_low)) +
  geom_tile(color = "white") +
  labs(
    title = "Food Security in Adults by Education and Poverty Level",
    x = "Poverty Level",
    y = "Education Level",
    fill = "Percentage\nLow Food Security"
  ) +
  scale_fill_viridis_c(option = "turbo", direction = 1) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5)
  )
```
##Age Distribution
```{r}

df_age_summary <- df_full %>%
  filter(Age > 17) %>% filter(comb_sec_adult != "Unknown" & !is.na(comb_sec_adult)) %>% filter(comb_sec_adult != "High or Marginal")

ggplot(df_age_summary, aes(x = Age, fill = comb_sec_adult)) +
  geom_density(alpha = 0.5) +
  labs(title = "Age Distribution and Food Security", x = "Age", y = "Density") +
  theme_classic() +  theme(legend.position = "none")


df_age_summary_child <- df_full %>%
  filter(Age < 18) %>% filter(comb_sec_child != "Unknown" & !is.na(comb_sec_child)) %>% filter(comb_sec_child != "High or Marginal")

ggplot(df_age_summary_child, aes(x = Age, fill = comb_sec_child)) +
  geom_density(alpha = 0.5) +
  labs(title = "Age Distribution and Food Security", x = "Age", y = "Density") +
  theme_classic() +  theme(legend.position = "none")
```

